layout_spectrum: 0.7762112
typography_spectrum: 0.4543069
color:
  saturation: 0.543941
  lightness: 0.1378042
  brandStrength: 0.1262753
  rhythmicContrast: 0.4546283
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: '160408'
